import type { Bill, DashboardStats } from '../types/bill';

export class DataLoader {
  private bills: Bill[] = [];

  async loadData(_dataPath: string = '../data/analyzed'): Promise<Bill[]> {
    try {
      // Try to load from the combined bills.json file generated by scripts/load-data.js
      const response = await fetch(`${import.meta.env.BASE_URL}bills.json`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();

      if (!Array.isArray(data)) {
        throw new Error('Invalid data format: expected array');
      }

      this.bills = this.normalizeBills(data);

      return this.bills;
    } catch (error) {
      // Return mock data for development
      return this.loadMockData();
    }
  }

  private normalizeBills(data: any[]): Bill[] {
    return data.map(bill => ({
      bill_id: bill.bill_id || bill.id || '',
      bill_number: bill.bill_number || bill.number || '',
      title: bill.title || '',
      url: bill.url || '',
      state: this.extractState(bill),
      year: this.extractYear(bill),
      session: bill.session || '',
      is_relevant: bill.is_relevant ?? true,
      relevance_reasoning: bill.relevance_reasoning || '',
      summary: bill.summary || '',
      bill_status: bill.bill_status || bill.status || 'Unknown',
      legislation_type: bill.legislation_type || bill.type || 'Bill',
      categories: bill.categories || [],
      tags: bill.tags || [],
      key_provisions: bill.key_provisions || [],
      palliative_care_impact: bill.palliative_care_impact || '',
      exclusion_check: bill.exclusion_check || '',
      special_flags: bill.special_flags || [],
      status_date: bill.status_date || '',
      last_action: bill.last_action || '',
      similarity_score: bill.similarity_score,
      distance: bill.distance,
    }));
  }

  private extractState(bill: any): string {
    // Try to extract state from various possible fields
    if (bill.state) return bill.state;
    if (bill.bill_number) {
      // Extract from bill number if it contains state code (e.g., "CT-SB01071")
      const match = bill.bill_number.match(/^([A-Z]{2})-/);
      if (match) return match[1];
    }
    // Default to extracting from file name or session
    if (bill.session && bill.session.includes('CT')) return 'CT';
    return 'Unknown';
  }

  private extractYear(bill: any): string {
    if (bill.year) return String(bill.year);
    if (bill.session) {
      const match = bill.session.match(/(\d{4})/);
      if (match) return match[1];
    }
    return new Date().getFullYear().toString();
  }

  private loadMockData(): Bill[] {
    // Mock data for development/testing
    return [
      {
        bill_id: '1932259',
        bill_number: 'SB01071',
        title: 'An Act Concerning Healthcare Workforce Development',
        url: 'https://legiscan.com/CT/bill/SB01071/2025',
        state: 'CT',
        year: '2025',
        session: '2025 Regular Session',
        is_relevant: true,
        summary: 'This bill addresses healthcare workforce shortages...',
        bill_status: 'Pending',
        legislation_type: 'Bill',
        categories: ['Workforce', 'Clinical Skill-Building'],
        tags: ['healthcare', 'workforce', 'training'],
        key_provisions: ['Establishes training programs', 'Creates grant funding'],
        palliative_care_impact: 'High impact on workforce development',
        exclusion_check: 'Passed',
        special_flags: [],
      },
      {
        bill_id: '1932260',
        bill_number: 'HB05234',
        title: 'An Act Concerning Pediatric Palliative Care Access',
        url: 'https://legiscan.com/CT/bill/HB05234/2025',
        state: 'CT',
        year: '2025',
        session: '2025 Regular Session',
        is_relevant: true,
        summary: 'Expands pediatric palliative care services...',
        bill_status: 'Enacted',
        legislation_type: 'Bill',
        categories: ['Pediatric Palliative Care', 'Patient Rights'],
        tags: ['pediatric', 'access', 'palliative care'],
        key_provisions: ['Requires insurance coverage', 'Establishes care standards'],
        palliative_care_impact: 'Direct expansion of services',
        exclusion_check: 'Passed',
        special_flags: [],
      },
    ];
  }

  getBills(): Bill[] {
    return this.bills;
  }

  getStats(): DashboardStats {
    const stats: DashboardStats = {
      totalBills: this.bills.length,
      byState: {},
      byCategory: {},
      byYear: {},
      byStatus: {},
      byLegislationType: {},
    };

    this.bills.forEach(bill => {
      // Count by state
      if (bill.state) {
        stats.byState[bill.state] = (stats.byState[bill.state] || 0) + 1;
      }

      // Count by category
      bill.categories?.forEach(category => {
        stats.byCategory[category] = (stats.byCategory[category] || 0) + 1;
      });

      // Count by year
      if (bill.year) {
        const year = String(bill.year);
        stats.byYear[year] = (stats.byYear[year] || 0) + 1;
      }

      // Count by status
      if (bill.bill_status) {
        stats.byStatus[bill.bill_status] = (stats.byStatus[bill.bill_status] || 0) + 1;
      }

      // Count by legislation type
      if (bill.legislation_type) {
        stats.byLegislationType[bill.legislation_type] =
          (stats.byLegislationType[bill.legislation_type] || 0) + 1;
      }
    });

    return stats;
  }
}
